// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: candles.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCandles = `-- name: GetCandles :many
SELECT instrument_id, timeframe, ts, open, high, low, close, volume, provider
FROM candles
WHERE instrument_id = $1
  AND timeframe = $2
  AND ts >= $3
  AND ts <= $4
ORDER BY ts DESC
LIMIT $5
`

type GetCandlesParams struct {
	InstrumentID uuid.UUID `json:"instrument_id"`
	Timeframe    string    `json:"timeframe"`
	Ts           time.Time `json:"ts"`
	Ts_2         time.Time `json:"ts_2"`
	Limit        int32     `json:"limit"`
}

func (q *Queries) GetCandles(ctx context.Context, arg GetCandlesParams) ([]Candle, error) {
	rows, err := q.db.Query(ctx, getCandles,
		arg.InstrumentID,
		arg.Timeframe,
		arg.Ts,
		arg.Ts_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Candle{}
	for rows.Next() {
		var i Candle
		if err := rows.Scan(
			&i.InstrumentID,
			&i.Timeframe,
			&i.Ts,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCandle = `-- name: InsertCandle :one
INSERT INTO candles (
    instrument_id,
    timeframe,
    ts,
    open,
    high,
    low,
    close,
    volume,
    provider
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (instrument_id, timeframe, ts)
DO UPDATE SET
    open = EXCLUDED.open,
    high = EXCLUDED.high,
    low = EXCLUDED.low,
    close = EXCLUDED.close,
    volume = EXCLUDED.volume,
    provider = EXCLUDED.provider
RETURNING instrument_id, timeframe, ts, open, high, low, close, volume, provider
`

type InsertCandleParams struct {
	InstrumentID uuid.UUID      `json:"instrument_id"`
	Timeframe    string         `json:"timeframe"`
	Ts           time.Time      `json:"ts"`
	Open         pgtype.Numeric `json:"open"`
	High         pgtype.Numeric `json:"high"`
	Low          pgtype.Numeric `json:"low"`
	Close        pgtype.Numeric `json:"close"`
	Volume       pgtype.Numeric `json:"volume"`
	Provider     string         `json:"provider"`
}

func (q *Queries) InsertCandle(ctx context.Context, arg InsertCandleParams) (Candle, error) {
	row := q.db.QueryRow(ctx, insertCandle,
		arg.InstrumentID,
		arg.Timeframe,
		arg.Ts,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
		arg.Provider,
	)
	var i Candle
	err := row.Scan(
		&i.InstrumentID,
		&i.Timeframe,
		&i.Ts,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.Provider,
	)
	return i, err
}
