// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instruments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getInstrumentBySymbolExchangeAssetClass = `-- name: GetInstrumentBySymbolExchangeAssetClass :one
SELECT id, symbol, asset_class, exchange, currency, created_at
FROM instruments
WHERE symbol = $1
  AND (
    exchange = $2
    OR (exchange IS NULL AND $2::text IS NULL)
  )
  AND asset_class = $3
`

type GetInstrumentBySymbolExchangeAssetClassParams struct {
	Symbol     string      `json:"symbol"`
	Exchange   pgtype.Text `json:"exchange"`
	AssetClass string      `json:"asset_class"`
}

func (q *Queries) GetInstrumentBySymbolExchangeAssetClass(ctx context.Context, arg GetInstrumentBySymbolExchangeAssetClassParams) (Instrument, error) {
	row := q.db.QueryRow(ctx, getInstrumentBySymbolExchangeAssetClass, arg.Symbol, arg.Exchange, arg.AssetClass)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.AssetClass,
		&i.Exchange,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const upsertInstrument = `-- name: UpsertInstrument :one
INSERT INTO instruments (id, symbol, asset_class, exchange, currency)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (symbol, exchange, asset_class)
DO UPDATE SET
    currency = EXCLUDED.currency
RETURNING id, symbol, asset_class, exchange, currency, created_at
`

type UpsertInstrumentParams struct {
	ID         uuid.UUID   `json:"id"`
	Symbol     string      `json:"symbol"`
	AssetClass string      `json:"asset_class"`
	Exchange   pgtype.Text `json:"exchange"`
	Currency   string      `json:"currency"`
}

func (q *Queries) UpsertInstrument(ctx context.Context, arg UpsertInstrumentParams) (Instrument, error) {
	row := q.db.QueryRow(ctx, upsertInstrument,
		arg.ID,
		arg.Symbol,
		arg.AssetClass,
		arg.Exchange,
		arg.Currency,
	)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.AssetClass,
		&i.Exchange,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
