// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mt5_trades.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMT5AccountSnapshot = `-- name: GetMT5AccountSnapshot :one
SELECT
    COUNT(*)::bigint AS total_trades,
    MAX(imported_at) AS last_imported_at
FROM mt5_trades
WHERE account_id = $1
`

type GetMT5AccountSnapshotRow struct {
	TotalTrades    int64       `json:"total_trades"`
	LastImportedAt interface{} `json:"last_imported_at"`
}

func (q *Queries) GetMT5AccountSnapshot(ctx context.Context, accountID uuid.UUID) (GetMT5AccountSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getMT5AccountSnapshot, accountID)
	var i GetMT5AccountSnapshotRow
	err := row.Scan(&i.TotalTrades, &i.LastImportedAt)
	return i, err
}

const getMT5EquityFallback = `-- name: GetMT5EquityFallback :many
SELECT
    day,
    SUM(day_profit) OVER (ORDER BY day)::numeric AS equity
FROM (
    SELECT DATE(opened_at) AS day, COALESCE(SUM(profit), 0)::numeric AS day_profit
    FROM mt5_trades
    WHERE account_id = $1
    GROUP BY DATE(opened_at)
) x
ORDER BY day
`

type GetMT5EquityFallbackRow struct {
	Day    pgtype.Date    `json:"day"`
	Equity pgtype.Numeric `json:"equity"`
}

func (q *Queries) GetMT5EquityFallback(ctx context.Context, accountID uuid.UUID) ([]GetMT5EquityFallbackRow, error) {
	rows, err := q.db.Query(ctx, getMT5EquityFallback, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMT5EquityFallbackRow{}
	for rows.Next() {
		var i GetMT5EquityFallbackRow
		if err := rows.Scan(&i.Day, &i.Equity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMT5EquityFromDaily = `-- name: GetMT5EquityFromDaily :many
SELECT
    day,
    SUM(total_profit) OVER (ORDER BY day)::numeric AS equity
FROM mt5_analytics_daily
WHERE account_id = $1
ORDER BY day
`

type GetMT5EquityFromDailyRow struct {
	Day    pgtype.Date    `json:"day"`
	Equity pgtype.Numeric `json:"equity"`
}

func (q *Queries) GetMT5EquityFromDaily(ctx context.Context, accountID uuid.UUID) ([]GetMT5EquityFromDailyRow, error) {
	rows, err := q.db.Query(ctx, getMT5EquityFromDaily, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMT5EquityFromDailyRow{}
	for rows.Next() {
		var i GetMT5EquityFromDailyRow
		if err := rows.Scan(&i.Day, &i.Equity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMT5Summary = `-- name: GetMT5Summary :one
SELECT
    COUNT(*)::bigint AS total_trades,
    COALESCE(SUM(profit), 0)::numeric AS total_profit,
    COALESCE(AVG(profit), 0)::numeric AS avg_profit,
    COALESCE(SUM(CASE WHEN profit > 0 THEN 1 ELSE 0 END), 0)::bigint AS winners,
    COALESCE(SUM(CASE WHEN profit < 0 THEN 1 ELSE 0 END), 0)::bigint AS losers,
    COALESCE(
        SUM(CASE WHEN profit > 0 THEN 1 ELSE 0 END)::numeric
        / NULLIF(COUNT(*)::numeric, 0),
        0
    )::numeric AS win_rate,
    (
        SUM(CASE WHEN profit > 0 THEN profit ELSE 0 END)
        / NULLIF(ABS(SUM(CASE WHEN profit < 0 THEN profit ELSE 0 END)), 0)
    )::numeric AS profit_factor,
    COALESCE(MAX(profit), 0)::numeric AS max_profit,
    COALESCE(MIN(profit), 0)::numeric AS min_profit
FROM mt5_trades
WHERE account_id = $1
`

type GetMT5SummaryRow struct {
	TotalTrades  int64          `json:"total_trades"`
	TotalProfit  pgtype.Numeric `json:"total_profit"`
	AvgProfit    pgtype.Numeric `json:"avg_profit"`
	Winners      int64          `json:"winners"`
	Losers       int64          `json:"losers"`
	WinRate      pgtype.Numeric `json:"win_rate"`
	ProfitFactor pgtype.Numeric `json:"profit_factor"`
	MaxProfit    pgtype.Numeric `json:"max_profit"`
	MinProfit    pgtype.Numeric `json:"min_profit"`
}

func (q *Queries) GetMT5Summary(ctx context.Context, accountID uuid.UUID) (GetMT5SummaryRow, error) {
	row := q.db.QueryRow(ctx, getMT5Summary, accountID)
	var i GetMT5SummaryRow
	err := row.Scan(
		&i.TotalTrades,
		&i.TotalProfit,
		&i.AvgProfit,
		&i.Winners,
		&i.Losers,
		&i.WinRate,
		&i.ProfitFactor,
		&i.MaxProfit,
		&i.MinProfit,
	)
	return i, err
}

const insertMT5Trade = `-- name: InsertMT5Trade :execrows
INSERT INTO mt5_trades (
    account_id,
    ticket,
    symbol,
    side,
    volume,
    open_price,
    close_price,
    opened_at,
    closed_at,
    commission,
    swap,
    profit,
    comment,
    source_hash,
    imported_at
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
ON CONFLICT (account_id, source_hash) DO NOTHING
`

type InsertMT5TradeParams struct {
	AccountID  uuid.UUID          `json:"account_id"`
	Ticket     string             `json:"ticket"`
	Symbol     string             `json:"symbol"`
	Side       string             `json:"side"`
	Volume     pgtype.Numeric     `json:"volume"`
	OpenPrice  pgtype.Numeric     `json:"open_price"`
	ClosePrice pgtype.Numeric     `json:"close_price"`
	OpenedAt   time.Time          `json:"opened_at"`
	ClosedAt   pgtype.Timestamptz `json:"closed_at"`
	Commission pgtype.Numeric     `json:"commission"`
	Swap       pgtype.Numeric     `json:"swap"`
	Profit     pgtype.Numeric     `json:"profit"`
	Comment    pgtype.Text        `json:"comment"`
	SourceHash string             `json:"source_hash"`
	ImportedAt time.Time          `json:"imported_at"`
}

func (q *Queries) InsertMT5Trade(ctx context.Context, arg InsertMT5TradeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMT5Trade,
		arg.AccountID,
		arg.Ticket,
		arg.Symbol,
		arg.Side,
		arg.Volume,
		arg.OpenPrice,
		arg.ClosePrice,
		arg.OpenedAt,
		arg.ClosedAt,
		arg.Commission,
		arg.Swap,
		arg.Profit,
		arg.Comment,
		arg.SourceHash,
		arg.ImportedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recomputeMT5AnalyticsDaily = `-- name: RecomputeMT5AnalyticsDaily :execrows
WITH daily AS (
    SELECT
        DATE(opened_at) AS day,
        COUNT(*)::int AS total_trades,
        COALESCE(SUM(CASE WHEN profit > 0 THEN 1 ELSE 0 END), 0)::int AS winners,
        COALESCE(SUM(CASE WHEN profit < 0 THEN 1 ELSE 0 END), 0)::int AS losers,
        COALESCE(SUM(profit), 0)::numeric AS total_profit,
        COALESCE(AVG(profit), 0)::numeric AS avg_profit,
        COALESCE(MAX(profit), 0)::numeric AS max_profit,
        COALESCE(MIN(profit), 0)::numeric AS min_profit,
        (
            SUM(CASE WHEN profit > 0 THEN profit ELSE 0 END)
            / NULLIF(ABS(SUM(CASE WHEN profit < 0 THEN profit ELSE 0 END)), 0)
        )::numeric AS profit_factor,
        COALESCE(
            SUM(CASE WHEN profit > 0 THEN 1 ELSE 0 END)::numeric
            / NULLIF(COUNT(*)::numeric, 0),
            0
        )::numeric AS win_rate
    FROM mt5_trades
    WHERE account_id = $1
    GROUP BY DATE(opened_at)
)
INSERT INTO mt5_analytics_daily (
    id,
    account_id,
    day,
    total_trades,
    winners,
    losers,
    total_profit,
    avg_profit,
    max_profit,
    min_profit,
    profit_factor,
    win_rate,
    created_at,
    updated_at
)
SELECT
    (
        substr(md5($1::text || ':' || day::text), 1, 8) || '-' ||
        substr(md5($1::text || ':' || day::text), 9, 4) || '-' ||
        substr(md5($1::text || ':' || day::text), 13, 4) || '-' ||
        substr(md5($1::text || ':' || day::text), 17, 4) || '-' ||
        substr(md5($1::text || ':' || day::text), 21, 12)
    )::uuid,
    $1,
    day,
    total_trades,
    winners,
    losers,
    total_profit,
    avg_profit,
    max_profit,
    min_profit,
    profit_factor,
    win_rate,
    NOW(),
    NOW()
FROM daily
ON CONFLICT (account_id, day) DO UPDATE SET
    total_trades = EXCLUDED.total_trades,
    winners = EXCLUDED.winners,
    losers = EXCLUDED.losers,
    total_profit = EXCLUDED.total_profit,
    avg_profit = EXCLUDED.avg_profit,
    max_profit = EXCLUDED.max_profit,
    min_profit = EXCLUDED.min_profit,
    profit_factor = EXCLUDED.profit_factor,
    win_rate = EXCLUDED.win_rate,
    updated_at = NOW()
`

func (q *Queries) RecomputeMT5AnalyticsDaily(ctx context.Context, accountID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, recomputeMT5AnalyticsDaily, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
