// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTagToTrade = `-- name: AddTagToTrade :exec
INSERT INTO trade_tags (trade_id, tag_id)
VALUES ($1, $2)
ON CONFLICT (trade_id, tag_id) DO NOTHING
`

type AddTagToTradeParams struct {
	TradeID pgtype.UUID `json:"trade_id"`
	TagID   pgtype.UUID `json:"tag_id"`
}

func (q *Queries) AddTagToTrade(ctx context.Context, arg AddTagToTradeParams) error {
	_, err := q.db.Exec(ctx, addTagToTrade, arg.TradeID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, user_id, name)
VALUES ($1, $2, $3)
RETURNING id, user_id, name
`

type CreateTagParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.ID, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE id = $1
  AND user_id = $2
`

type DeleteTagParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.UserID)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, user_id, name
FROM tags
WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id pgtype.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const listTagsByTrade = `-- name: ListTagsByTrade :many
SELECT t.id, t.user_id, t.name
FROM tags t
JOIN trade_tags tt ON tt.tag_id = t.id
WHERE tt.trade_id = $1
ORDER BY t.name ASC
`

func (q *Queries) ListTagsByTrade(ctx context.Context, tradeID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByTrade, tradeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByUser = `-- name: ListTagsByUser :many
SELECT id, user_id, name
FROM tags
WHERE user_id = $1
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type ListTagsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListTagsByUser(ctx context.Context, arg ListTagsByUserParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromTrade = `-- name: RemoveTagFromTrade :exec
DELETE FROM trade_tags
WHERE trade_id = $1
  AND tag_id = $2
`

type RemoveTagFromTradeParams struct {
	TradeID pgtype.UUID `json:"trade_id"`
	TagID   pgtype.UUID `json:"tag_id"`
}

func (q *Queries) RemoveTagFromTrade(ctx context.Context, arg RemoveTagFromTradeParams) error {
	_, err := q.db.Exec(ctx, removeTagFromTrade, arg.TradeID, arg.TagID)
	return err
}
