// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trades.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTrade = `-- name: CreateTrade :one
INSERT INTO trades (
    id,
    user_id,
    instrument_id,
    side,
    qty,
    entry_price,
    exit_price,
    opened_at,
    closed_at,
    fees,
    notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, COALESCE($10, 0), $11)
RETURNING id, user_id, instrument_id, side, qty, entry_price, exit_price, opened_at, closed_at, fees, notes
`

type CreateTradeParams struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	InstrumentID uuid.UUID          `json:"instrument_id"`
	Side         string             `json:"side"`
	Qty          pgtype.Numeric     `json:"qty"`
	EntryPrice   pgtype.Numeric     `json:"entry_price"`
	ExitPrice    pgtype.Numeric     `json:"exit_price"`
	OpenedAt     time.Time          `json:"opened_at"`
	ClosedAt     pgtype.Timestamptz `json:"closed_at"`
	Column10     interface{}        `json:"column_10"`
	Notes        pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error) {
	row := q.db.QueryRow(ctx, createTrade,
		arg.ID,
		arg.UserID,
		arg.InstrumentID,
		arg.Side,
		arg.Qty,
		arg.EntryPrice,
		arg.ExitPrice,
		arg.OpenedAt,
		arg.ClosedAt,
		arg.Column10,
		arg.Notes,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstrumentID,
		&i.Side,
		&i.Qty,
		&i.EntryPrice,
		&i.ExitPrice,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.Fees,
		&i.Notes,
	)
	return i, err
}

const listTradesByUser = `-- name: ListTradesByUser :many
SELECT id, user_id, instrument_id, side, qty, entry_price, exit_price, opened_at, closed_at, fees, notes
FROM trades
WHERE user_id = $1
ORDER BY opened_at DESC
LIMIT $2 OFFSET $3
`

type ListTradesByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListTradesByUser(ctx context.Context, arg ListTradesByUserParams) ([]Trade, error) {
	rows, err := q.db.Query(ctx, listTradesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trade{}
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstrumentID,
			&i.Side,
			&i.Qty,
			&i.EntryPrice,
			&i.ExitPrice,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.Fees,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
