name: ci

on:
  push:
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Go test
        working-directory: apps/api
        run: go test ./...

      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: apps/api
          args: ./...
